name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: format
        run: bun run format

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: lint
        run: bun run lint --format=github

  typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: typecheck
        run: bun run typecheck
